### PR TITLE
feat: add support for labels

### LINKED ISSUE #102: Feature request: to create a PR with a label
Would it be possible to extend this plugin to give support to creating a PR with a label?

Relates to https://github.com/wolfy1339/octoherd-script-remove-eol-node-versions/issues/3

### PR DESCRIPTION
**Pull request by stefanbuck**
Fixes #102 

### Gotchas
- When running against an existing pull request it does not remove any previous set labels. This could cause confusion, especially if a previous run was using another label e.g. had a typo. 
- If user doesn't have permissions to add labels, it still creates the PR but without labels. Do we want to log an info to the console?

### CODE REVIEW

**Comment by gr2m** [comment]
> * If user doesn't have permissions to add labels, it still creates the PR but without labels. Do we want to log an info to the console?

Yes I think that'd be good

> * When running against an existing pull request it does not remove any previous set labels. This could cause confusion, especially if a previous run was using another label e.g. had a typo.

We could log something as well, to explain that labels are added, not replaced?

**Comment by gr2m** [comment]
> Should I be using `console.log` like in other places or move all logging to `octokit.log`?

I'd always use `octokit.log` in the context of Octokit plugins.

**Comment by stefanbuck** [comment]
Took me some time to return to this pull request, but you can find the latest changes in e60b64947234d3c0da3a91e06874c739e95408ac

**Review by gr2m — APPROVED** [review]
great PR, thanks!

**Comment by stefanbuck** [comment]
> great PR, thanks!

Just following the breadcrumbs here

**Comment by stefanbuck** [comment]
That said, updating the fixtures isn't straight forward, but I can't think of a better way.

**Comment by oscard0m** [comment]
Thanks for this contribution @stefanbuck ❤️

**Pull request merged**
