### PR TITLE
feat: `author` and `committer` options

### PR DESCRIPTION
**Pull request by tylermichael**
This PR allows you to pass in the author and/or the committer for a change.

### CODE REVIEW

**Comment by tylermichael** [comment]
@gr2m Hi, could you please allow the tests to run?

**Comment by gr2m** [comment]
can you update the readme usage example please?

**Comment by tylermichael** [comment]
I've updated the readme, as well as made the test action use `npm test` to hopefully address the error where the command `jest` wasn't found.

**Comment by tylermichael** [comment]
Hey @gr2m, could you allow the tests to run again? Thanks!

**Review by gr2m — APPROVED** [review]
thank you!

**Pull request merged**
